### ISSUE TITLE
Could NOT find CURL when building.

### ISSUE THREAD

**Issue by stephenhouser** [vancluever/homebrew-input-leap#4]
macOS 13.5.1 on M2 Mini.
---

```
brew install input-leap
==> Fetching vancluever/input-leap/input-leap
==> Cloning https://github.com/vancluever/input-leap.git
Updating /Users/houser/Library/Caches/Homebrew/input-leap--git
Fetching submodule ext/gtest
Fetching submodule ext/gulrak-filesystem
==> Checking out branch vancluever-homebrew-tip
Already on 'vancluever-homebrew-tip'
Your branch is up to date with 'origin/vancluever-homebrew-tip'.
HEAD is now at d30a5098 Revert "only allows active client grabbing clipboard"
Entering 'ext/gtest'
Entering 'ext/gulrak-filesystem'
/Users/houser/Library/Caches/Homebrew/input-leap--git/ext/gtest
/Users/houser/Library/Caches/Homebrew/input-leap--git/ext/gulrak-filesystem
==> Installing input-leap from vancluever/input-leap
==> Patching
==> ./clean_build.sh
Last 15 lines from /Users/houser/Library/Logs/Homebrew/input-leap/01.clean_build.sh:
-- Looking for include file sys/socket.h
-- Looking for include file sys/socket.h - found
-- Looking for include file sys/utsname.h
-- Looking for include file sys/utsname.h - found
-- Looking for getpwuid_r
-- Looking for getpwuid_r - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Could NOT find CURL (missing: CURL_LIBRARY CURL_INCLUDE_DIR)
CMake Error at CMakeLists.txt:90 (message):
  Missing library: curl


-- Configuring incomplete, errors occurred!

If reporting this issue please do so at (not Homebrew/brew or Homebrew/homebrew-core):
  https://github.com/vancluever/homebrew-input-leap/issues
```

**Comment by vancluever** [comment]
@stephenhouser did you get this resolved? Sorry for the delay in replying.

I have run into this issue a couple of times, but transiently. MacOS (since Big Sur) ships with a [dynamic linker cache](https://developer.apple.com/documentation/macos-release-notes/macos-big-sur-11_0_1-release-notes#Kernel) that essentially keeps curl (and other common shared libraries) out of the file system, which can cause confusion with builds when it breaks (there's plenty of documentation on the internet about it).

Usually, when it happened to me it happened right after installing XCode (and possibly the command-line tools too). A reboot corrected it, as far as I can remember.

I'm going to close this now as there's not really much we can do about it on this end. When input-leap eventually releases and there are binary builds that can just be bottled, this will be a non-issue.

Thanks!

**Comment by timtlin** [comment]
Hi @stephenhouser,

I had this problem with my M2 MacBook (Ventura 13.6, curl installed via Homebrew) and solved it by linking the curl dependencies to /usr/local, i.e.:

sudo ln -s /opt/homebrew/opt/curl/include/curl /usr/local/include
sudo ln -s /opt/homebrew/opt/curl/lib/libcurl.dylib /usr/local/lib

before running brew install input-leap.
